# Generated by Django 4.1.7 on 2023-04-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название сайта')),
                ('descriptions', models.TextField(verbose_name='описание сайта')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='логотип сайта')),
                ('phone', models.CharField(max_length=100, verbose_name='Тел.ном')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('adress', models.CharField(max_length=250, verbose_name='Адресс')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('instagram', models.URLField(verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки айта',
            },
        ),
    ]
